### ISSUE TITLE
Getting Error when trying to read base

### ISSUE THREAD

**Issue by wifff** [matthewjrogers/rairtable#10]
I moved from my Mac to an Ubuntu machine getting a strange error from code, that works on MacOS.

set_airtable_api_key('pat0TSQcD.....SECRET')
airtable_base_id = 'appgRIfj...SECRET'

table <- airtable('Assessments', airtable_base_id)
assessments <- read_airtable(table)

Error in data.table::rbindlist(dta, use.names = TRUE, fill = TRUE) :
Column 17 of item 1 is length 3 inconsistent with column 1 which is length 100. Only length-1 columns are recycled.
(works on the Mac)

> sessionInfo()
R version 4.2.3 (2023-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS

other attached packages:
 [1] fmsb_0.7.5       kableExtra_1.3.4 scales_1.2.1     ggplot2_3.4.1    rairtable_0.1.1  dplyr_1.1.1      sqldf_0.4-11     RSQLite_2.3.0    gsubfn_0.7       proto_1.0.0     
[11] knitr_1.42

The Mac is running
R 4.2.1, airtable_0.1.1  dplyr_1.1.0

Best regards and many thanks
Wolfgang

**Comment by matthewjrogers** [comment]
Hi Wolfgang,
Is this the CRAN release of `rairtable` and likely involves either a user or multiple select field? If so, I think this is a known issue and resolved in `dev`. I suggest installing the development version using `remotes::install_github('matthewjrogers/rairtable', ref = 'dev')`.  You can see the old issue [here](https://github.com/matthewjrogers/rairtable/issues/4)

I am hoping to get the time to push these fixes to CRAN soon -- it has defied my best intentions for a while but expect to get it done sooner than later!

**Comment by wifff** [comment]
Hi Matt,
it works with the dev version !!!
Thank you very much for your quick help and this VERY cool piece of software !

Best regards, Wolfgang

**Comment by matthewjrogers** [comment]
Excellent! Glad the package is helpful
