### ISSUE TITLE
No values in Airtable column => corresponding column is not created in the R dataframe

### ISSUE THREAD

**Issue by wifff** [matthewjrogers/rairtable#17]
When the column of a Airtable table is empty, the corresponding column in R is not created.
As soon as an arbitrary value is inserted in an arbitrary row of the Airtable table the column is created in the R dataframe as expected.

I am using rairtable 0.1.2 on a Mac.

Many thanks for your help & best regards
Wolfgang

**Comment by matthewjrogers** [comment]
The Airtable API excludes empty columns from the JSON payload and unfortunately it is not possible to override this behavior. It's admittedly not an ideal user experience from the perspective of this package, but one we're priced into.

**Comment by wifff** [comment]
Strange API design by Airtable - hope that they will change that one day  :-/ 
Thank you VERY much for your superfast feedback !
