### ISSUE TITLE
Automatically create new Single or Multi select options.

### ISSUE THREAD

**Issue by StefanMusch** [matthewjrogers/rairtable#7]
**Describe the bug**
When trying to add new rows from a data.frame in a Single or Multi select column, the following error is given:
```
Error: Error in POST. Error Code 422: Unprocessable entity. The request was well-formed but was unable to be followed due to semantic errors.

Ensure that the column types in R are compatible with the column types of your Airtable table.
```
The reason here is that the options in the data frame aren't added to the selection yet. However, in many occasions, you don't know the options in advance. 

The solution here is to add new unique options that aren't present in the column yet. After doing some digging, I found [this implementation in a different package](https://github.com/bergant/airtabler/pull/17). Is this something you can add to `rairtable` (which is better maintained and has a better UI). 

**To Reproduce**

Where `Status` is a Single Select column

```
x <- tibble(status = c("Done", "To Do", "In Progress"))
insert_records(x, base)
```

**Comment by matthewjrogers** [comment]
Hey there @StefanMusch -- yes, I should be able to add this functionality. I appreciate the legwork you did tracking down that existing implementation. 

I intend to do some housekeeping for `rairtable` around the end of the month when I have some time off. I'm optimistic I'll be able to get this functionality into the next CRAN release.

**Comment by StefanMusch** [comment]
Hey @matthewjrogers
Thanks for the quick update, that'd be amazing. I found [this piece](https://help.landbot.io/article/irr67ey7pl-how-to-add-update-different-types-of-fields-in-airtable#force_format_typecast_true) which could be helpful in understanding what the `typecast` does specifically.

**Comment by matthewjrogers** [comment]
@StefanMusch this is resolved in `dev`. To access the changes, you can install with `remotes::install_github('matthewjrogers/rairtable', ref = 'dev')`. I'm going to send updates to CRAN in the next week.
